import yt
import sys


def load_mesh(f):

    # use yt.load() to auto detect the type of mesh
    mesh = yt.load(f)

    # mesh should be type MoabHex8Dataset
    return mesh

def get_isosurfaces(mesh):

    # current process here not supported for PyNE Meshes

    # find the min and max weight window, and the associated locations
    min_ww, min_loc = mesh.find_min("ww_n")
    max_ww, max_loc = mesh.find_max("ww_n")
    #print(min_ww, min_loc)
    #print(max_ww, max_loc)

    # method for finding a value at a specific point
    #print(mesh.find_field_values_at_point("ww_n", [0.,0.,0.]))

    dd = mesh.all_data()
    # dd should now be type MoabHex8Mesh
    dd.extract_isocontours("ww_n", 0.002, "test.obj", True)

    #print(mesh.field_list)
    #mesh.surface(mesh, 'ww_n', 0.1)




def main():

    # load in mesh file
    # this should be .h5m mesh generated by pyne that includes ww tags
    f = sys.argv[1]
    mesh = load_mesh(f)

    # attempt to get iso_contours from
    get_isosurfaces(mesh)



if __name__ == "__main__":
    main()
