import yt
import sys
import numpy as np

def load_mesh(f):

    # use yt.load() to auto detect the type of mesh
    mesh = yt.load(f)

    # mesh should be type MoabHex8Dataset
    return mesh

def get_isosurfaces(mesh):

    # current process here not supported for PyNE Meshes

    # find the min and max weight window, and the associated locations
    min_ww, min_loc = mesh.find_min("ww_n")
    max_ww, max_loc = mesh.find_max("ww_n")
    #print(min_ww, min_loc)
    #print(max_ww, max_loc)

    # method for finding a value at a specific point
    #print(mesh.find_field_values_at_point("ww_n", [0.,0.,0.]))

    dd = mesh.all_data()
    # dd should now be type MoabHex8Mesh
    dd.extract_isocontours("ww_n", 0.002, "test.obj", True)

    #print(mesh.field_list)
    #mesh.surface(mesh, 'ww_n', 0.1)


def convert_to_uniform(mesh):

    left = mesh.domain_left_edge
    right = mesh.domain_right_edge
    dims = mesh.domain_dimensions
    print(mesh.field_list)

    data = mesh.all_data()

    print(type(data))

    # print(data.field_list)
    ww_data = data['ww_n']
    print(data['idx'])
    idx_data = data['idx']
    #
    # print('idx')
    d = {'ww_n':ww_data, 'idx':idx_data}
    #
    # print(ww_data.shape)
    #
    # arr = np.random.random((128, 128, 128))
    #print(arr.shape)
    #
    # #obj = mesh.arbitrary_grid(left, right, dims)
    #
    ds = yt.load_uniform_grid(d, dims)
    print(ds.field_list)
    #
    # #d = ds.all_data()
    # #
    # ds.extract_isocontours("ww_n", 0.02, "test.obj", True)


def main():

    # load in mesh file
    # this should be .h5m mesh generated by pyne that includes ww tags
    f = sys.argv[1]
    mesh = load_mesh(f)

    # attempt to get iso_contours from
    # get_isosurfaces(mesh)

    convert_to_uniform(mesh)



if __name__ == "__main__":
    main()
